- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
When the trigger phrase is specified in the build config and when the build trigger is set up to trigger on every push, the comment being null causes null reference exception.
> small null reference fix in merge trigger after ghprb

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRootAction.java
Github can send hook events either in json format or in urlencoded format. Ghprb supports only the latter one, which is confusing and not convenient sometimes. This change adds JSON format support.
> Added support for JSON Github requests

- pom.xml
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbITBaseTestCase.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRepositoryTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbTestUtil.java
The latest API replaces the getUrl method for pull requests with getHtmlUrl.
Fixed #74
> Updated to latest github-api.

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRootAction.java
When delivering payloads to a Jenkins with CSRF enabled(crumbs), the
request is forbidden with `No valid crumb was included in the request`.
The added `GhprbRootActionCrumbExclusion` class tells Jenkins that this
root action does not required crumbs.
> Exclude the plugin root action from crumbs

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
Switch around the `null` check to prevent this NPE:
```
2015-05-14 15:05:22.055+1200 [id=64]    WARNING hudson.triggers.Trigger#checkTriggers: org.jenkinsci.plugins.ghprb.GhprbTrigger.run() failed for hudson.model.FreeStyleProject@####[JOBNAME]
java.lang.NullPointerException
at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:155)
......
```
@reviewbybees
> Fix null pointer exception if the helper method is null.

- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbBuilds.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRepository.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTriggerBackwardsCompatible.java
- src/main/java/org/jenkinsci/plugins/ghprb/extensions/GhprbCommitStatus.java
- src/main/java/org/jenkinsci/plugins/ghprb/extensions/GhprbCommitStatusException.java
- src/main/java/org/jenkinsci/plugins/ghprb/extensions/comments/GhprbBuildLog.java
- src/main/java/org/jenkinsci/plugins/ghprb/extensions/comments/GhprbBuildResultMessage.java
- src/main/java/org/jenkinsci/plugins/ghprb/extensions/comments/GhprbBuildStatus.java
- src/main/java/org/jenkinsci/plugins/ghprb/extensions/comments/GhprbCommentFile.java
- src/main/java/org/jenkinsci/plugins/ghprb/extensions/comments/GhprbPublishJenkinsUrl.java
- src/main/java/org/jenkinsci/plugins/ghprb/extensions/status/GhprbNoCommitStatus.java
- src/main/java/org/jenkinsci/plugins/ghprb/extensions/status/GhprbSimpleStatus.java
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/config.jelly
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/global.jelly
- src/main/resources/org/jenkinsci/plugins/ghprb/extensions/status/GhprbSimpleStatus/config.jelly
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRepositoryTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/extensions/status/GhprbSimpleStatusTest.java
Move the commit status to an extension.  
Default to updating the status, but added an extension that does nothing if that is the desired behavior.  
This is also configured on a per job basis.
> Commit status

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbBuilds.java
It would seem there are two cases where getMergeable() returns null, if GitHub hasn't settled or if the pull request was already merged.  These shouldn't cause the onStart to hang forever.  
Comments are now added if either of the two cases happens, or if one minute just isn't the right time to wait for GitHub to settle.  Fixes #96
> Fix infinite hang if getMergeable never returns a boolean

- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/config.groovy
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/global.groovy
If there is no instance of the plugin, then the groovy config script dies, and the configure page won't load.
> Bug with groovy config

- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbGitHubAuth.java
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbGitHubAuth/config.groovy
Attempt to fix jenkinsci/ghprb-plugin#117, also fix jenkinsci/ghprb-plugin#119
Also adds a permissions check for specified repos.
> Work for fixing credentials issues

- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbGitHubAuth.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- Actually use the new path generated as a fix in
jenkinsci/ghprb-plugin#122
- Use URIRequirementBuilder instead of manually building a requirements
list
- Add logging around accessing credentials to debug failures, and give
better error messages when something is wrong
- General refactoring of a few methods to reduce code duplication
I've tested this on my Jenkins instance, and it seems to fix the issues I addressed, as well as providing helpful debugging messages in the logs.
It seems that anonymous requests are still occasionally being used; I'm not sure if the github-api library is occasionally falling back on failures.
Fully fixes #117.
> Fix credentials bugs as noted in jenkinsci/ghprb-plugin#117

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRootAction.java
[JENKINS-29322](https://issues.jenkins-ci.org/browse/JENKINS-29322)
Note that `extractRequestBody` already uses `ServletRequest.getReader` to do some kind of decoding, so I am not sure if it even correct to ask for the request encoding when processing the URL decoding of that already-decoded text. However this is the most conservative change since if this was null, the code would definitely hit the bug, so we cannot be doing any worse.
@reviewbybees
> [JENKINS-29322] ServletRequest.getEncoding may be null

- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
If a project is set to "trigger only", and an admin adds the test/retest phrase in a comment, nothing would happen. The logs would display "Trigger only phrase but we are not triggered". This is because the `triggered` variable was set to true on every other instance of manually triggering a build, **except** when an admin made the comment.
This probably (read: definitely) warrants an additional test, but I don't have a setup java environment nor have I ever previously done testing in java. If you ask and just leave this PR out I'll get to it eventually, otherwise if you want this fix merged sooner (and tested) someone else will have to do that.
EDIT:
I've also found that adding a user to the whitelist doesn't mark existing PR's by that person as accepted (which is expected, since that …
> Fix condition where admin can't run tests

- pom.xml
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
The problem was that job.getBuilds() would return the ongoing matrix
root build, causing to build the previous SHA1 in case a commit was not
the first of the pull request.
The current fix breaks the “smart changes” logic for matrix jobs.
A proper fix that preserves this functionality because it would be very
hard to determine which is a root build of the same run, especially if
the concurrent builds options is enabled.
The PR also simplifies some logic.
> Use the correct SHA1 for Matrix builds

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge/config.jelly
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge/global.jelly
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge/help-onlyTriggerPhrase.html
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMergeTest.java
1. Fix NPEs where `triggerSender` is not available
2. Infer intent to merge based on comment trigger
3. If merge can only triggered by comment and there is no comment, there is no intent to merge, therefore do not fail or check other conditions
4. Do not post comments about commentors not being Admins etc if build is triggered by automation
connected to #158, fixes #158
> Fixing NPE and non-sensical behavior of the GHPRB

- src/main/java/org/jenkinsci/plugins/ghprb/extensions/status/GhprbSimpleStatus.java
The commit status that would be created in onEnvironmentSetup() would
happen right after the one from onBuildStart() and thus would wipe
whatever the user wanted to have set there as their startedStatus string
(or e.g.  if the user had specified "--none--" to avoid any update at
all). Remove that status update since it is superfluous.
> Don't create a commit status in onEnvironmentSetup()

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRepository.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRootAction.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbWebHook.java
Webhook logs should only be generated once, and each job doesn't need to handle the processing of the body to an object.
> Reduce noise of webhook handling for many jobs

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTriggerBackwardsCompatible.java
This fixes issues where the configVersion doesn't get saved  to the config.xml.
Any changes to the plugin don't get saved until the job changes manually, this way the configVersion will get updated as things get updated.
> Save job settings when the trigger starts

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbBuildListener.java
Currently manually started builds fail with NPE:
```
FATAL: null
java.lang.NullPointerException
at org.jenkinsci.plugins.ghprb.GhprbBuildListener.setUpEnvironment(GhprbBuildListener.java:40)
at hudson.model.AbstractBuild$AbstractBuildExecution.createLauncher(AbstractBuild.java:575)
at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:495)
at hudson.model.Run.execute(Run.java:1741)
at hudson.matrix.MatrixBuild.run(MatrixBuild.java:301)
at hudson.model.ResourceController.execute(ResourceController.java:98)
at hudson.model.Executor.run(Executor.java:408)
Finished: FAILURE
```
> Prevent NPE when job started manually

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRepository.java
If it returns false, then ghRepository will not be set, which will cause us to eventually loop around and attempt to call init again (and again)
> During init, we should check whether initGhRepository returns false

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRepository.java
When using a differnet jenkins url (see https://github.com/jenkinsci/ghprb-plugin/pull/223) the shared secret wasn't being set in the github URL.  As such any received requests came through with:
SEVERE: Request doesn't contain a signature. Check that github has a secret that should be attached
to the hook
This adds the secret. Not sure how this worked beforehand - maybe it wasn't tested with autocreated hooks?
> set shared secret in webhook

- src/main/java/org/jenkinsci/plugins/ghprb/HttpConnectorWithJenkinsProxy.java
[JENKINS-31827](https://issues.jenkins-ci.org/browse/JENKINS-31827)
> [JENKINS-31827] Use default timeouts for URLConnections

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
Fixed janinko/ghprb#372
Fixed janinko/ghprb#351
The problem was in trying to get the global if there wasn't a local configuration setup.  The update is required, but can be set up in a way so that it doesn't actually update the commit status.
> Fix config

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRootAction.java
* amz linux
* glassfish 4.1
* java 1.8.0_66
The log is
```
Payload is null, maybe content type {0} is not supported by this plugin. Please use application/json or application/x-www-form-urlencoded
```
after fix the parameters format:
```
Payload is null, maybe content type 'application/x-www-form-urlencoded;charset=UTF-8' is not supported by this plugin. Please use application/json or application/x-www-form-urlencoded
```
> Fix log and accepted content type

- pom.xml
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbContextExtensionPoint.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbExtensionContext.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbSimpleStatusContext.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbTriggerContext.java
This is the first step to move the Job DSL for GhprbTrigger from the Job DSL Plugin to the GitHub Pull Request Builder plugin.
I copied the existing DSL syntax to keep compatibility, only the `pullRequest` method has been renamed to `githubPullRequest` to avoid confusion with other pull request builder plugins.
DSL example:
```groovy
job('example') {
triggers {
githubPullRequest {
admin('USER_ID')
userWhitelist('you@you.com')
orgWhitelist(['your_github_org', 'another_org'])
cron('H/5 * * * *')
triggerPhrase('Ok to test')
onlyTriggerPhrase()
useGitHubHooks()
permitAll()
autoCloseFailedPullRequests()
allowMembersOfWhitelistedOrgsAsAdmin()
extensions {
commitStatus {
context('deploy to staging site')
startedStatus('deploying to staging site...')
statusUrl('http://mystatussite.com/prs') …
```
> [JENKINS-31214] added Job DSL for GhprbTrigger

- README.md
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbContextExtensionPoint.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbTriggerContext.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbUpstreamStatusContext.java
1) Added displayBuildErrorsOnDownstreamBuilds and whiteListTargetBranches DSL fields for setting the upstream job with triggering commit statuses from downstream jobs and setting whitelisted branches
```
githubPullRequest {
cron('*/1 * * * *')
useGitHubHooks()
permitAll()
displayBuildErrorsOnDownstreamBuilds() // New: Used for enabling commit statuses from downstream jobs
whiteListTargetBranches(['master','test', 'test2']) // New: Used for creating whiteList TargetBranches
}
```
2) Added new DslExtensionMethod for setting the commit status for downstream jobs
```
downstreamCommitStatus {
context('CONTEXT NAME')
triggeredStatus("The job has triggered")
startedStatus("The job has started")
statusUrl()
completedStatus('SUCCESS', "The job has passed")
completedStatus('FAILURE', "The job has …
```
> JENKINS-32375: GHPRB - Add DSL Support for Downstream Commit Status and Whitelist Target Branches

- src/main/java/org/jenkinsci/plugins/ghprb/upstream/GhprbUpstreamStatus.java
When no build result message is set, the `completedStatus` variable appears to be `null`, making the plugin crash with the following stack trace:
```
java.lang.NullPointerException
at org.jenkinsci.plugins.ghprb.upstream.GhprbUpstreamStatus.makeBuildVariables(GhprbUpstreamStatus.java:42)
at hudson.model.AbstractBuild.getBuildVariables(AbstractBuild.java:1056)
at org.jenkinsci.plugins.envinject.service.EnvInjectVariableGetter.getBuildVariables(EnvInjectVariableGetter.java:108)
at org.jenkinsci.plugins.envinject.EnvInjectListener.setUpEnvironmentWithoutJobPropertyObject(EnvInjectListener.java:233)
at org.jenkinsci.plugins.envinject.EnvInjectListener.setUpEnvironment(EnvInjectListener.java:46)
at hudson.model.AbstractBuild$AbstractBuildExecution.createLauncher(AbstractBuild.java:572)
at …
```
> Fixed NPE when no build result message is set on Jenkins

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRootAction.java
Avoids a lot of unneeded API calls that will return 404
> Use message metadata to determine whether issue_comment is pull request

- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRepository.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTriggerBackwardsCompatible.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbContextExtensionPoint.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbITBaseTestCase.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMergeTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRepositoryTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbTestUtil.java
Moving the current states of any open PRs to the job config , or keeping it in the plugin config, isn't a very good option.   Several issues have been created based on the trigger saving those configs many times, and those same files are sometimes kept historically causing a lot of noise.  
This PR moves that status into the build directory, which can then be filtered by change tracking systems.  This also lays the groundwork for multiple GitHub repositories to be handles by one job trigger.
> Move PR data to its own config

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbBuilds.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRepository.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTriggerBackwardsCompatible.java
- src/main/java/org/jenkinsci/plugins/ghprb/extensions/comments/GhprbPublishJenkinsUrl.java
- src/main/java/org/jenkinsci/plugins/ghprb/extensions/status/GhprbSimpleStatus.java
- src/test/java/org/jenkinsci/plugins/ghprb/GeneralTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbTestUtil.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbTriggerTest.java
Fixes #243 
For any web facing classes the getters need to use get and not is or they won't be picked up when accessing the configuration page.
> All getters should use get, and not is

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
Should fix https://github.com/janinko/ghprb/issues/389
Even though last build ID is not null, the actual build may have been removed from jenkins, most likely if the job is configured to keep only that last N builds.
This will ensure the build is not null before getting the build data.
> Fix NPE when last build has been deleted

- README.md
It appears `githubPullRequest` should actually be `pullRequest` according to [this source](https://jenkinsci.github.io/job-dsl-plugin/#method/javaposse.jobdsl.dsl.helpers.triggers.TriggerContext.pullRequest).
When using `githubPullRequest` as exemplified in the README, I had been seeing the following when attempting to run:
```
javaposse.jobdsl.dsl.DslScriptException: (script, line 39) No signature of method: 
javaposse.jobdsl.dsl.helpers.triggers.TriggerContext.githubPullRequest() is applicable 
for argument types: (script$_run_closure1_closure5_closure12) values: 
[script$_run_closure1_closure5_closure12@411c321a]
```
> update 'githubPullRequest' to 'pullRequest' in Job DSL section of README

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
@DavidTanner I saw this just looking at the code.  Should this not be setAccepted(true) here?  Otherwise there is no state change in the if at all.
> If user is accepted after PR was opened, we should actually set as accepted

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRootAction.java
If the trigger isn't set up properly (for instance, a missing github URL), catch the Exception so that the failure doesn't block other triggers
> If the trigger is not set up properly, catch Exception

- pom.xml
- src/main/java/org/jenkinsci/plugins/ghprb/extensions/GhprbExtensionDescriptor.java
Copy the list of extensions returned from Jenkins, then filter it for desired functionality.
The core version of Jenkins needed to be updated to address issues with MatrixProjects.
Fixes #231
> List of extensions was mutated

- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
If a trigger regex is invalid, exceptions may be thrown and it could block other legs from starting.  Handle gracefully
> Handle bad trigger regex gracefully

- pom.xml
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRootAction.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRootActionTest.java
Fixes #307 by handling the trigger execution in separate threads, thus not blocking the http handlers.
> Handle webhooks in separate threads

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRepository.java
- src/main/java/org/jenkinsci/plugins/ghprb/extensions/build/GhprbCancelBuildsOnUpdate.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMergeTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRepositoryTest.java
This change reduces the number of API calls made by the ghprb plugin.  .NET CI was hitting rate limits pretty regularly.  There are a few major improvements:
* When using webhooks, we do not check comments (pull comment data) except when absolutely necessary.   We recieve all the comment info through the hooks, so we only need to check for updated comments when we have a new pull request or when jenkins restarts.
* Never force a GH pull request update when a comment update comes through.  If a comment update came through, we're using webhooks and will have gotten the updated PR event.
* initGhRepository isn't necessary when a GhprbRepository is created.  It's not used in the pull request trigger init, and causes an API call.  It can be called on demand as necessary.  This also …
> Reduce API calls

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/global.groovy
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbTestUtil.java
Add an option to not have the GHPRB manage its webhooks.  This is preferable in cases where we have a lot of projects pointing at the same repo, or when the ghprb account has no admin access to the repo
> Add option to avoid managing of webhooks

- src/main/java/org/jenkinsci/plugins/ghprb/extensions/status/GhprbSimpleStatus.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbContextExtensionPoint.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbExtensionContext.java
- src/main/java/org/jenkinsci/plugins/ghprb/upstream/GhprbUpstreamStatus.java
- src/main/java/org/jenkinsci/plugins/ghprb/upstream/GhprbUpstreamStatusListener.java
- src/main/resources/org/jenkinsci/plugins/ghprb/upstream/GhprbUpstreamStatus/config.jelly
- src/main/resources/org/jenkinsci/plugins/ghprb/upstream/GhprbUpstreamStatus/help-showMatrixStatus.html
This pull request contains the solution for  [https://github.com/jenkinsci/ghprb-plugin/issues/301](https://github.com/jenkinsci/ghprb-plugin/issues/301).
It adds the ability to allow the user to not post commit statuses for the child job of a parent matrix job. If the checkbox is for this function is not pressed, it will follow its default behaviour.
I've added a checkbox in the config.jelly file that saves the value in "showMatrixStatus". The GhprbSimpleStatus class will read the value of the field. If the value is false it will create a commit status and proceed as normal (!showMatrixStatus). If the value is true, then will check if the project is a matrix project. Since the children jobs are not Matrix projects, we can avoid posting commit statuses for them by checking both the value …
> Adding functionality to not post commit status for children jobs

- src/main/java/org/jenkinsci/plugins/ghprb/extensions/status/GhprbSimpleStatus.java
- src/main/java/org/jenkinsci/plugins/ghprb/upstream/GhprbUpstreamStatusListener.java
- src/main/resources/org/jenkinsci/plugins/ghprb/upstream/GhprbUpstreamStatus/config.jelly
Fixes janinko/ghprb#390; the 'addTestResults' flag is missing from the GhprbUpstreamStatus ui entirely, and GhprbUpstreamStatusListener is parsing 'ghprbStartedStatus' instead of 'ghprbAddTestResults'.
> Add one-line test output option for upstream status

- src/main/java/org/jenkinsci/plugins/ghprb/upstream/GhprbUpstreamStatusListener.java
A PR to fix issue #345
* Ensure that we're only getting the environmental variables once and create a new instance of GhprbSimpleStatus when we post one, so race conditions don't occur.
> When downstream jobs are triggered at the same time, the commit statuses overwrite each others

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRepositoryTest.java
The paged comment check is expensive, and when a new PR is opened, there are no comments, so we can avoid the check.  This value is updated whenever the PR data is pulled, so it will be updated properly during non-webhook and webhook scnearios.
> Avoid comments check if there are no comments

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
I fixed a bug in the Java Github API where it would always populate certain fields of the structure regardless of whether they had been pulled before (the case is unmerged PR).  Doing so causes the mergeability check to fail because we will never pull new data.  Instead, if the mergeability is null, grab the PR again.
> Pull PR data if necessary when determining mergeability

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRootAction.java
```
java.lang.NullPointerException
at org.jenkinsci.plugins.ghprb.GhprbRootAction.doIndex(GhprbRootAction.java:79)
at sun.reflect.GeneratedMethodAccessor828.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:320)
at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:163)
at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
at org.kohsuke.stapler.IndexDispatcher.dispatch(IndexDispatcher.java:26)
at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
... 69 more
```
> Fix NullPointerException

- README.md
- pom.xml
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbContextExtensionPoint.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbPullRequestMergeContext.java
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge/config.jelly
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge/help-allowMergeWithoutTriggerPhrase.html
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMergeTest.java
Adds a new checkbox parameter to the merger post build action that allows merging without a trigger phrase if configured like that.
>  Merge only works when trigger phrase is present #257 

- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbContextExtensionPoint.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbTriggerContext.java
This PR adds supports of setting the build description template in Job DSL extension
> Add build description template to Job DSL extension

- README.md
- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbContextExtensionPoint.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbTriggerContext.java
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/config.groovy
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/help-blackListTargetBranches.html
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRepositoryTest.java
This allows for more flexible PR building, since you can say that a PR builds for everything except for specific branches.  While this may be able to be done using the current setup and some complicated regular expressions, I think have a clear blacklist is a more ideal implementation.
> Allow for blacklisting of target branches

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRepository.java
Since the description and title also make it into the builds as
variables, the edited hook should also be a valid trigger to trigger new
builds when these pieces of data change.
One use-case is validations on the description message to include a
proper change log.
> Handle "edited" pull-request hooks

- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRootActionTest.java
This test fails when running tests without an internet connection. The
following is an example stacktrace:
```
java.net.UnknownHostException: api.github.com
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:579)
at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:618)
at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getN …
```
> Fix mockito usage in test.

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
The ghprbPullTitle field not being escaped is causing issues with scripts that attempt to use the title, causing random failures based on the title of the pull request. Further, because the issues are at the script level, you can't work around the issue in the script itself. An example of a bug caused by this is https://github.com/dotnet/roslyn/issues/14480. This ports https://github.com/janinko/ghprb/pull/426.
> Escaped text in the pull title, so it can be safely used in scripts.

- README.md
- pom.xml
- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbContextExtensionPoint.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbTriggerContext.java
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/config.groovy
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/global.groovy
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRepositoryTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbTestUtil.java
This adds the `Whitelist label option` to ghprb's advanced options.
* If both Whitelist and Blacklist label options are entered, it works in 'AND' mode. In other words, PR should not have Blacklist label and Whiltelist label should exist.
* If nothing is entered in the Whitelist label option, this option is ignored.
I think adding the Whitelist label option can help solve the #210 issue in the future.
* Bug Fix Included (#441)
1. LabelField's empty string check problem.
Https://github.com/sjstyle/ghprb-plugin/commit/c54a32cb01d897c207a1f531aa3873f8ab70e044#diff-4b618248c9f9a59094a30a1212e2d172R170
Previously this plug-in did not check for Empty on this line. As a result, when the user enters a setting value, a non-null space is input, so the empty collection is always returned and the …
> Add whitelist label option.

- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/help-triggerPhrase.html
Other fields have an example of a regexp (such as the skip phrase)
or call it out in the Help.
We were excited to realize we could use this feature after an upgrade.
> Update help in app (it's correct in the README).

- README.md
I've found the various triggering mechanisms.  Part of my confusion has come from the fact that the example uses the same phrase for `triggerPhrase()` that is defined [in the code for `okToTestPhrase`](https://github.com/jenkinsci/ghprb-plugin/blob/master/src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java#L657).
The fact that the same string was used for both made it very difficult to understand what I was seeing in the logs....
> Don't use okToTestPhrase as triggerPhrase

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbBuilds.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbBuildsTest.java
"--none--" is treated as a special string by the build status component, but not by the component which actually posts back to the PR, leading to PRs which look like this:
https://github.com/apache/beam/pull/1706
This change will ensure the PR post follows the same rules and comes into line with the documentation.
Build Status code is [here](https://github.com/jenkinsci/ghprb-plugin/blob/master/src/main/java/org/jenkinsci/plugins/ghprb/extensions/status/GhprbSimpleStatus.java#L211).
Documentation [here](https://github.com/jenkinsci/ghprb-plugin/blob/master/CHANGELOG.md#--128).
> Consume --none-- in Github commenter.

- README.md
Only fetch the pull request needed for the job.
We ([Team Kodi](https://github.com/xbmc)) have 11701 pull request in https://github.com/xbmc/xbmc and the inital fetching of the repos needs some time.
> [readme] optimize fetching by only fetch the needed PR

- README.md
- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbContextExtensionPoint.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbTriggerContext.java
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/config.groovy
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/config.jelly.tmp
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/global.groovy
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/global.jelly.tmp
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/help-blackListCommitAuthor.html
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRepositoryTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbTestUtil.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbTriggerTest.java
GitHub PullRequest Builder provides functionality for triggering a Jenkins build on PR commit or comment from specific users. There is a specific use case when commits are made by build bots (checking in build artifacts into PullRequest as a result of the Jenkins build job). In such cases, under current conditions we inevitably running into a "recursive" build scenario, where each build commit will trigger a subsequent build.
Add ability to *skip build* if commits are made by users indicated in `Skip Build Commit Author` list configuration (see screen shot)
```
Feb 23, 2017 4:51:41 PM org.jenkinsci.plugins.ghprb.GhprbRootAction handleAction
INFO: Checking issue comment 'test this please' for repo MyOrg/MyProject
Feb 23, 2017 4:51:41 PM org.jenkinsci.plugins.ghprb.GhprbTrigger …
```
> Skip build on specific user commits

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRepositoryTest.java
If a github user has no name the log shows `[null] Added comment:`.
With this change it will fallback to the nickname.
> [PullRequest] log senders login ID if name == null

- pom.xml
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRepository.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/test/java/org/jenkinsci/plugins/ghprb/GeneralTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbIT.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbITBaseTestCase.java
This PR is two folded. The first commits holds a lot of whitespace fixes. 
The second commit is the actually change. It moves the creating of the hook into a runnable, which makes it way faster on startup. 
I have choosen a fixed thread pool with five executors. Not sure if this is a good value or not :)
> Make startHook not blocking jenkins startup

- pom.xml
- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
This change provides an admin the ability to better control how GhprbTrigger initializes.
- Convert existing system properties to use standards from Jenkins core.  This is necessary to sanitize user input to ensure that system properties are properly handled.  This also integrates with Jenkins system logging when a user accidentally misconfigures a property.
- Add a system property to disable registering GitHub webhooks on startup.  This assumes that hooks were already properly registered when an admin or user created the Jenkins job.
- Implements recommendations from #535
This change provides the following system properties:
- `org.jenkinsci.plugins.ghprb.GhprbTrigger.poolSize=N` where `N` is an integer defining number of threads to use for registering webhooks on startup.
- …
> Disable register hooks on startup via property

- AUTHORS.md
- CHANGELOG.md
- pom.xml
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRepositoryTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRootActionTest.java
The `github-api` has been bumped up to 1.90 to roll in the fixes from jenkinsci/github-api-plugin#16. This should take care of #580 and the duplicate #587. Notable things here:
* Rethrowing of `IOException` in a `RuntimeException` to mitigate API changes from 1.90 `github-api` dependency in `GhprbPullRequest`
* Patched up tests for API changes with some quick casts
* The plugin is compiling and all tests run with `mvn clean test` are passing
If we cut a release off of this, it will include the updates from #543 that went in recently. I've added notes to the `CHANGELOG.md` to make this obvious and quicker to get to a release. Let me know if I can help speed this along, and I'll try to do what I can.
> Handle 64-bit commit id from new github-api

- README.md
Be more descriptive about the difference between using sha1 and ghprbactualcommit in the branch specifier.
Closes #563
> Improve description of branch specifier in config

- CHANGELOG.md
- pom.xml
Looking through the reflog & compile dependencies, this dependency is not needed.
It has a dependency on bouncy-castle, which can get complicated. We're removing
unnecessary complexity with this change.
> Remove dependency.

- pom.xml
ref: https://wiki.jenkins.io/display/JENKINS/GitHub+pull+request+builder+plugin
The intent of this change is to reflect in Jenkins wiki metadata the current active maintainers.  This is so Jenkins users have an up to date list of points of contact for this plugin.
For now, I've removed @janinko and @valdisrigdon since I haven't seen them post in a while.  If you guys don't want to be removed, then comment in this PR and let me know you want your ID to remain.  I'll wait ~1 week before merging this for your feedback.
@jenkinsci/ghprb-plugin-developers after this change is merged I recommend you following up with PRs to add yourselves if you wish to be reflected as a point of contact in the Jenkins wiki.
> Update list of current maintainers

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbCause.java
[JENKINS-48950](https://issues.jenkins-ci.org/browse/JENKINS-48950)
Testing:
@reviewbybees esp. @oleg-nenashev
> [JENKINS-48950] [JEP-200] Stop trying to serialize github-api types

- pom.xml
This makes use of Maven profiles to activate skipping checkstyle only when releasing.
Fixes #620
> Skip checkstyle only when releasing

- src/main/java/org/jenkinsci/plugins/ghprb/extensions/status/GhprbSimpleStatus.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRepositoryTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/extensions/status/GhprbSimpleStatusTest.java
Previously, the messages were "Build triggered sha1 is {merged,original
commit}." (note the lack of full-stop after "triggered") and "Build
started. sha1 is {merged,original commit}.". Make these consistent, and
make the message clearer: "Build {triggered,started} for
{merge,original} commit."
> Improve "Build triggered/started" messages

- RELEASE.md
This adds a RELEASE.md for maintainers to agree and standardize on how to release the GHPRB plugin.
@bjoernhaeuser please review.  Also, I'm going to let you perform the first release following this document.  This way you get to see what releasing is like (i.e. gain experience with releasing).  If need be, we can pair on a release via video chatting.
> Document a formalized release process

- src/test/java/org/jenkinsci/plugins/ghprb/extensions/status/GhprbSimpleStatusTest.java
From test run 21 on Jenkins:
```
06:22:00 [windows] Argument(s) are different! Wanted:
06:22:00 [windows] ghRepository.createCommitStatus(
06:22:00 [windows]     "sha",
06:22:00 [windows]     PENDING,
06:22:00 [windows]     "",
06:22:00 [windows]     "Build triggered. sha1 is original commit.",
06:22:00 [windows]     isNull()
06:22:00 [windows] );
06:22:00 [windows] -> at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatusTest.testUseDefaultContext(GhprbSimpleStatusTest.java:168)
06:22:00 [windows] Actual invocation has different arguments:
06:22:00 [windows] ghRepository.createCommitStatus(
06:22:00 [windows]     "sha",
06:22:00 [windows]     PENDING,
06:22:00 [windows]     "",
06:22:00 [windows]     "Build triggered for original commit.",
06:22:00 [windows]     
```
Should …
> Fix test GhprbSimpleStatusTest.testUseDefaultContext

- src/main/java/org/jenkinsci/plugins/ghprb/extensions/comments/GhprbCommentFile.java
If the comment file was completely empty it was still read, surrounded
with a header and a footer, and posted as a comment on the pull request.
This is just noise IMHO.
This commit makes it so that the message stays empty if the file was empty.
@Ippo343 @samrocketman FYI this is #647 with the merge conflict solved. Did not have any access to the new origin, therefore cherry-picked it.
> Avoid posting a comment for empty comment files

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRepository.java
This is a breaking change. So it highly encouraged from github to set
this to "0", therefore going down this way.
This closes #596
@marcokrikke @samrocketman What do you think about this? Should this be configurable?
> Use ssl validation for webhook

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRepository.java
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/help-useGitHubHooks.html
When a system property `jenkins.ghprb.webhook.insecure` is set to `true`,
GitHub webhooks created by GHPRB will have SSL certificate verification
disabled. This is useful in case the Jenkins server is available via HTTPS
with a self-signed or corporate CA issued certificate.
Resolves #694
> add an option to disable SSL certificate verification in GitHub webhooks

- src/main/java/org/jenkinsci/plugins/ghprb/extensions/build/GhprbCancelBuildsOnUpdate.java
- src/test/java/org/jenkinsci/plugins/ghprb/extensions/build/GhprbCancelBuildsOnUpdateTest.java
The `GhprbCancelBuildsOnUpdate`'s `cancelCurrentBuilds` does not loop through the project's queue items which will cause an infinite loop when new scheduled builds are added. In certain cases the newly scheduled jobs using Ghprb will get caught in the loop and will deadlock the executor and worker threads. See the stacktrace below. 
```
Executor #0 for <Redacted>: executing job #284
"Executor #0 for <Redacted> : executing job #284" Id=46759 Group=main BLOCKED on org.jenkinsci.plugins.ghprb.GhprbPullRequest@71a5579b owned by "Thread-3400" Id=45802
at org.jenkinsci.plugins.ghprb.GhprbPullRequest.setPullRequest(GhprbPullRequest.java:836)
-  blocked on org.jenkinsci.plugins.ghprb.GhprbPullRequest@71a5579b
at org.jenkinsci.plugins.ghprb.GhprbPullRequest.getPullRequest(GhprbPullRequest.java:827) …
```
> GhprbCancelBuildsOnUpdate loops through queue items

- README.md
- checkstyle.xml
- pom.xml
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestTest.java
The method gitHttpTransportUrl has been removed from github-api (see commit https://github.com/github-api/github-api/commit/944d92bbb408dc7be91fcbe539a21762c6e0491a?diff=split). And because of that the ghprb plugin is broken. This change correct the issue.
> update to support breaking change in github-api

- README.md
The GitHub Pull Request Builder plugin should be deprecated so that users do not mistakenly install it when integrating with GitHub.
More details are available in Jenkins infrastructure help desk ticket:
* https://github.com/jenkins-infra/helpdesk/issues/4608
The documentation for plugins.jenkins.io is being updated at:
* https://github.com/jenkins-infra/plugins-wiki-docs/pull/8
The deprecation message is being added here as one more location that declares the plugin is deprecated.
Confirmed that the page looks correct in its other implementation in:
* https://github.com/jenkins-infra/plugins-wiki-docs/pull/8
> Deprecate GitHub Pull Request Builder plugin
