- src/main/java/org/jenkinsci/plugins/ghprb/extensions/status/GhprbSimpleStatus.java
- src/main/java/org/jenkinsci/plugins/ghprb/manager/GhprbBuildManager.java
- src/main/java/org/jenkinsci/plugins/ghprb/manager/impl/GhprbBaseBuildManager.java
Replacement for https://github.com/janinko/ghprb/pull/277 using the latest master.  Commit status and comments are now handled inside extensions.
> Directhex statistics on completion

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/config.groovy
Also fixed null pointer when no auths are set up.
> Bug with groovy config

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbGitHubAuth.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbGitHubAuth/config.groovy
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/config.groovy
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/global.groovy
Closes https://github.com/janinko/ghprb/issues/286
Closes https://github.com/janinko/ghprb/issues/287
> Add missing method and fix bug.

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbGitHubAuth.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRepository.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRootAction.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbWebHook.java
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbGitHubAuth/config.groovy
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/config.jelly.tmp
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMergeTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRepositoryTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRootActionTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbTestUtil.java
> Moliholy GitHub signature

- pom.xml
- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbGitHubAuth.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRepositoryTest.java
Added logging and some fixes for the credentials.
Fix the null pointers that are happening in pullRequestMerge
> Add logging, and fix merge.

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTriggerBackwardsCompatible.java
Fixes #131, and addresses the following issues:
https://github.com/janinko/ghprb/issues/301
https://github.com/janinko/ghprb/issues/300
https://github.com/janinko/ghprb/issues/299
https://github.com/jenkinsci/ghprb-plugin/issues/129
https://github.com/jenkinsci/ghprb-plugin/issues/124
And possibly other closed issues.
> Only keep the auth id in the job config

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRepositoryTest.java
> Fix issue introduced when consolidating logic

- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
> Conslo patch 1

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbBuilds.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/config.groovy
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/help-accessToken.html
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/help-buildDescTemplate.html
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/help-logExcerptLines.html
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/help-password.html
> Build Description is configurable per job.

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbWebHook.java
> Webhook repo checking now case insensitive

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
Fixed issue https://github.com/janinko/ghprb/issues/256 by adding details to logging
> Add details about the project url

- README.md
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbGitHubAuth.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbGitHubAuth/config.groovy
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge/config.jelly
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMergeTest.java
Fixed #146 
Fixed #145 
Added delete branch on merge.
> Extend the options in the merge step.

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbCrumbExclusion.java
Pull request is not triggered if Prevent Cross Site Request Forgery exploits is enabled
@reviewbybees
> [FIXED JENKINS-30483] Pull request is not triggered if CSR is enabled

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/main/java/org/jenkinsci/plugins/ghprb/extensions/status/GhprbSimpleStatus.java
> NPEs in 1.28

- src/main/java/org/jenkinsci/plugins/ghprb/extensions/status/GhprbSimpleStatus.java
More issues not addressed by #184, #185, and #186
> More places for NPE error

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbBuilds.java
- src/main/java/org/jenkinsci/plugins/ghprb/upstream/GhprbUpstreamStatus.java
This should fix #184 as well as other issues.
> Fix issues in 1.28 release

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java
> GhprbPullRequestMerge must NOT persist and serialize logger #192

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRepository.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRootAction.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbWebHook.java
Reverts jenkinsci/ghprb-plugin#190
Fixes #199, fixes #198
> Revert "Reduce noise of webhook handling for many jobs"

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTriggerBackwardsCompatible.java
> Config version fix

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
> Replace \r + " chars in addition in some env variables

- pom.xml
[JENKINS-31827](https://issues.jenkins-ci.org/browse/JENKINS-31827)
> [FIXED JENKINS-31827] Use github-api with explicit socket timeouts declared

- README.md
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbContextExtensionPoint.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbPullRequestMergeContext.java
> [JENKINS-31214] added Job DSL for GhprbPullRequestMerge and docs

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRepositoryTest.java
Fixes #250 
When the base of a PR has changed then we should treat it the same as having the head change.
> Add a check to see if the base of a PR has changed

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRepositoryTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbTriggerTest.java
> Add synchronization

- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
- src/main/java/org/jenkinsci/plugins/ghprb/extensions/status/GhprbSimpleStatus.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbContextExtensionPoint.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbExtensionContext.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbSimpleStatusContext.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbUpstreamStatusContext.java
- src/main/java/org/jenkinsci/plugins/ghprb/upstream/GhprbUpstreamStatus.java
- src/main/java/org/jenkinsci/plugins/ghprb/upstream/GhprbUpstreamStatusListener.java
- src/main/resources/org/jenkinsci/plugins/ghprb/extensions/status/GhprbSimpleStatus/config.jelly
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbTestUtil.java
> Test Results are optional, and off by default

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbGitHubAuth.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRepository.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
Fixes janinko/ghprb#395 If we sync on this then it can't ever be null.
> Synchronization on null

- pom.xml
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbIT.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRepositoryTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbTestUtil.java
Uses some of #287 so that I can release with a newer version of maven.
> Add the compile plugin for maven so it can be updated

- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbBranch.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbCause.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbGitHubAuth.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRepository.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRootAction.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbPullRequestMergeContext.java
- src/main/java/org/jenkinsci/plugins/ghprb/manager/GhprbBuildManager.java
- src/main/java/org/jenkinsci/plugins/ghprb/manager/factory/GhprbBuildManagerFactoryUtil.java
As recommended by #291, just without any code changes
> Fix errors in javadoc step.

- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
- src/main/java/org/jenkinsci/plugins/ghprb/extensions/build/GhprbCancelBuildsOnUpdate.java
Fixes #290 Setup only requires adding the extension to a job.
> Fixe NPE in cancel setup

- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java
> Merge comment is expanded.  User case ignored

- src/main/java/org/jenkinsci/plugins/ghprb/extensions/status/GhprbSimpleStatus.java
There were other places that checked this case but this one was missed.
> Avoid NPE if cause is null

- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbContextExtensionPoint.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbTriggerContext.java
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/config.groovy
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/config.jelly.tmp
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/help-skipBuildPhrase.html
Fixes and Implements #339 :
- Fixed the bug with inability to change the skip build phrase in a job.  It now stores it properly.
- Skip build phrase now checks in a pull request title as well as it's body.
- Added DSL Support for skip build phrase.
> Skip Build Phrase Fix and Improvements

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRepositoryTest.java
It would appear this field doesn't get populated correctly so don't use it for now.
> GetCommentsCount always returns 0 so comments never work

- README.md
Reverts jenkinsci/ghprb-plugin#276
> Revert "update 'githubPullRequest' to 'pullRequest' in Job DSL section of README"

- README.md
Reverts jenkinsci/ghprb-plugin#372
> Revert "update 'mergeGithubPullRequest' to 'mergePullRequest' in Job DSL sect…"

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbRepository.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbPullRequestMergeContext.java
Fixes #383 At least by avoiding the null pointer exception the config can be saved properly.  The underlying issue still exists, we were unable to get a valid reference to the repo.
> Null pointer

- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
I noticed this typo while browsing logfile output and figured I'd send a small
PR to fix it. This plugin is great btw!
> Typo in log statement

- README.md
- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbContextExtensionPoint.java
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/config.groovy
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/global.groovy
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRepositoryTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbTestUtil.java
Reverts jenkinsci/ghprb-plugin#431
> Revert "Add support for github labels ignore list"

- README.md
- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbContextExtensionPoint.java
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/config.groovy
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/global.groovy
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRepositoryTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbTestUtil.java
This reverts commit 6fe5895d283c8a70d245d86813626040112c0995.
This re-implements on #431.
CC @udisch
> Re-implement label ignore feature.

- src/main/java/org/jenkinsci/plugins/ghprb/upstream/GhprbUpstreamStatus.java
- src/main/java/org/jenkinsci/plugins/ghprb/upstream/GhprbUpstreamStatusListener.java
Putting this up for now; will ask for feedback on approach.
> Revert pipeline changes for the UpstreamStatusListener.

- src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbContextExtensionPoint.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbTriggerContext.java
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/config.groovy
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/help-excludedRegions.html
- src/main/resources/org/jenkinsci/plugins/ghprb/GhprbTrigger/help-includedRegions.html
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRepositoryTest.java
This adds the ability to define a list of regions to include
or exclude from the pull request builder trigger.
This should solve issue #221
> Add support to restrict pull requests to defined paths

- CHANGELOG.md
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbTriggerTest.java
Replaces #573, #575 
I forked the repository and added the tests, as described in #575.
> Better GitHub username check

- README.md
Added a clarification that adding text before or after `retest this please` in the same comment will trigger the build, after trying both.
> README update for new build

- README.md
- checkstyle.xml
- pom.xml
- src/main/java/org/jenkinsci/plugins/ghprb/extensions/comments/GhprbBuildStatus.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbBuildsTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbIT.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbITBaseTestCase.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMergeTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRepositoryTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbRootActionTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbTestUtil.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbTriggerTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/extensions/status/GhprbSimpleStatusTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/manager/configuration/JobConfigurationTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/manager/factory/GhprbBuildManagerFactoryUtilTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/manager/impl/GhprbDefaultBuildManagerTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/manager/impl/downstreambuilds/BuildFlowBuildManagerTest.java
- src/test/java/org/jenkinsci/plugins/ghprb/rules/JenkinsRuleWithBuildFlow.java
In #599 we added checkstyle config and formatted the code. 
This does the same for test code.
> Format README and test code

- pom.xml
- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestTest.java
This seems to fix the issue (tested locally with simple setup). That being said, I am not sure this is the best approach. Any comments are more than welcome.
edit by @samrocketman:
See also #267
> [#267] do not add duplicated comments asking for approval

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java
This has been running on our instance for several months and has the desired effect. I'm afraid there is no test for this issue included; I'm not a java programmer and wouldn't really know where to start.
--- edit from @samrocketman
Fixes #233
> Fix for stale ghprbCommentBody values (#233/JENKINS-40802)

- src/main/java/org/jenkinsci/plugins/ghprb/extensions/comments/GhprbCommentFile.java
> remove extra msg comments for build comment file

- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbCancelBuildsOnUpdateContext.java
- src/main/java/org/jenkinsci/plugins/ghprb/jobdsl/GhprbExtensionContext.java
Closes #628 
@bsudy @samrocketman please take a look :)
> Expose cancelBuildsOnUpdate to dsl

- README.md
> Updated minor inconsistencies in readme

- src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java
- src/test/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMergeTest.java
> Actually fail build if checked
